### PR TITLE
Renamed and merged crates

### LINKED ISSUE #36: Release to crates-io
0.0.8 has not made it here yet: https://crates.io/crates/prdoc

### PR DESCRIPTION
**Pull request by mutantcornholio**
@chevdor still owns the package on crates.io, and refuses to allow parity to publish it

And maybe instead of two crates, we only need one?

WDYT?

Fixes #36

### CODE REVIEW

**Comment by ggwpez** [comment]
Release engineering can also publish it: https://crates.io/crates/prdoc

**Comment by mutantcornholio** [comment]
However, we can't use Parity's [user](https://crates.io/users/parity-crate-owner) to publish it.  
As far as I understood it, I'd have to ask @Morganamilo or @EgorPopelyaev for their crates.io token to keep publishing it. 
Just as well as Will can revoke the access at any time (which seems probable, as he refuses to cooperate), and we can't do anything about it.

**Review by ggwpez — APPROVED** [review]

**Comment by ggwpez** [comment]
I spoke to Will and confirmed that it is okay to remove Rel-Eng as publisher and that Parity should fork.  
Then please go ahead with renaming the crate and setting up the publish pipeline again with the new name: `parity-prdoc`.  
Maybe we also rename the repo here, not sure.

PS: We could keep the binary name backwards compatible, so that it installs two binaries: `prdoc` and `parity-prdoc`. Then it would not break workflows.

**Comment by mutantcornholio** [comment]
> PS: We could keep the binary name backwards compatible, so that it installs two binaries: `prdoc` and `parity-prdoc`. Then it would not break workflows.

Why not just keep producing a single `prdoc` binary?  
Two _identical_ binaries seems a bit weird and excessive.  

> Maybe we also rename the repo here, not sure.

I think maybe just mention it in README and that's all? `paritytech/prdoc` still has "parity" in the name.

**Pull request merged**
